### ISSUE TITLE
no data file 

### ISSUE THREAD

**Issue by Minjuner-97** [yz-intelligence/AI-Competition#3]
Hello~ There are many <.DS_Store> file, such as feature file, and the original data in aliyun web cannot be downloaded.
could you please provide the data? 
thanks!

**Comment by Heitao5200** [comment]
<.DS_Store> 文件是mac系统自己产生的，并不是特征文件，特征文件在代码之中并没有保存；原始数据的下载地址在这里：https://tianchi.aliyun.com/competition/entrance/531947/information?lang=zh-cn

**Comment by Heitao5200** [comment]
你可以注册账号之后下载
